"""Utilitarios de bandeiras para selecoes da Copa."""

from __future__ import annotations

import re
import unicodedata
from typing import Dict


def _normalizar_texto(texto: object) -> str:
    bruto = unicodedata.normalize("NFKD", str(texto or ""))
    sem_acentos = "".join(ch for ch in bruto if not unicodedata.combining(ch))
    sem_separadores = re.sub(r"[^a-zA-Z0-9]+", " ", sem_acentos)
    return " ".join(sem_separadores.split()).strip().lower()


_FLAG_BY_NORMALIZED: Dict[str, str] = {
    _normalizar_texto("Brazil"): "🇧🇷",
    _normalizar_texto("Brasil"): "🇧🇷",
    _normalizar_texto("BR"): "🇧🇷",
    _normalizar_texto("BRA"): "🇧🇷",
    _normalizar_texto("Mexico"): "🇲🇽",
    _normalizar_texto("México"): "🇲🇽",
    _normalizar_texto("MX"): "🇲🇽",
    _normalizar_texto("MEX"): "🇲🇽",
    _normalizar_texto("South Africa"): "🇿🇦",
    _normalizar_texto("África do Sul"): "🇿🇦",
    _normalizar_texto("ZA"): "🇿🇦",
    _normalizar_texto("RSA"): "🇿🇦",
    _normalizar_texto("South Korea"): "🇰🇷",
    _normalizar_texto("Coreia do Sul"): "🇰🇷",
    _normalizar_texto("KR"): "🇰🇷",
    _normalizar_texto("KOR"): "🇰🇷",
    _normalizar_texto("Czechia"): "🇨🇿",
    _normalizar_texto("República Tcheca"): "🇨🇿",
    _normalizar_texto("CZ"): "🇨🇿",
    _normalizar_texto("CZE"): "🇨🇿",
    _normalizar_texto("Canada"): "🇨🇦",
    _normalizar_texto("Canadá"): "🇨🇦",
    _normalizar_texto("CA"): "🇨🇦",
    _normalizar_texto("CAN"): "🇨🇦",
    _normalizar_texto("Bosnia & Herzegovina"): "🇧🇦",
    _normalizar_texto("Bósnia e Herzegovina"): "🇧🇦",
    _normalizar_texto("Bósnia"): "🇧🇦",
    _normalizar_texto("BA"): "🇧🇦",
    _normalizar_texto("BIH"): "🇧🇦",
    _normalizar_texto("Qatar"): "🇶🇦",
    _normalizar_texto("Catar"): "🇶🇦",
    _normalizar_texto("QA"): "🇶🇦",
    _normalizar_texto("QAT"): "🇶🇦",
    _normalizar_texto("Switzerland"): "🇨🇭",
    _normalizar_texto("Suíça"): "🇨🇭",
    _normalizar_texto("CH"): "🇨🇭",
    _normalizar_texto("SUI"): "🇨🇭",
    _normalizar_texto("USA"): "🇺🇸",
    _normalizar_texto("US"): "🇺🇸",
    _normalizar_texto("United States"): "🇺🇸",
    _normalizar_texto("Estados Unidos"): "🇺🇸",
    _normalizar_texto("EUA"): "🇺🇸",
    _normalizar_texto("Argentina"): "🇦🇷",
    _normalizar_texto("AR"): "🇦🇷",
    _normalizar_texto("ARG"): "🇦🇷",
    _normalizar_texto("France"): "🇫🇷",
    _normalizar_texto("França"): "🇫🇷",
    _normalizar_texto("FR"): "🇫🇷",
    _normalizar_texto("FRA"): "🇫🇷",
    _normalizar_texto("England"): "🏴",
    _normalizar_texto("Inglaterra"): "🏴",
    _normalizar_texto("ENG"): "🏴",
    _normalizar_texto("Scotland"): "🏴",
    _normalizar_texto("Escócia"): "🏴",
    _normalizar_texto("SCO"): "🏴",
    _normalizar_texto("Portugal"): "🇵🇹",
    _normalizar_texto("PT"): "🇵🇹",
    _normalizar_texto("POR"): "🇵🇹",
    _normalizar_texto("Spain"): "🇪🇸",
    _normalizar_texto("Espanha"): "🇪🇸",
    _normalizar_texto("ES"): "🇪🇸",
    _normalizar_texto("ESP"): "🇪🇸",
    _normalizar_texto("Germany"): "🇩🇪",
    _normalizar_texto("Alemanha"): "🇩🇪",
    _normalizar_texto("DE"): "🇩🇪",
    _normalizar_texto("GER"): "🇩🇪",
    _normalizar_texto("Netherlands"): "🇳🇱",
    _normalizar_texto("Países Baixos"): "🇳🇱",
    _normalizar_texto("NL"): "🇳🇱",
    _normalizar_texto("NED"): "🇳🇱",
    _normalizar_texto("Japan"): "🇯🇵",
    _normalizar_texto("Japão"): "🇯🇵",
    _normalizar_texto("JP"): "🇯🇵",
    _normalizar_texto("JPN"): "🇯🇵",
    _normalizar_texto("Uruguay"): "🇺🇾",
    _normalizar_texto("Uruguai"): "🇺🇾",
    _normalizar_texto("UY"): "🇺🇾",
    _normalizar_texto("URU"): "🇺🇾",
    _normalizar_texto("Morocco"): "🇲🇦",
    _normalizar_texto("Marrocos"): "🇲🇦",
    _normalizar_texto("MA"): "🇲🇦",
    _normalizar_texto("MAR"): "🇲🇦",
    _normalizar_texto("Tunisia"): "🇹🇳",
    _normalizar_texto("Tunísia"): "🇹🇳",
    _normalizar_texto("TN"): "🇹🇳",
    _normalizar_texto("TUN"): "🇹🇳",
    _normalizar_texto("Egypt"): "🇪🇬",
    _normalizar_texto("Egito"): "🇪🇬",
    _normalizar_texto("EG"): "🇪🇬",
    _normalizar_texto("EGY"): "🇪🇬",
    _normalizar_texto("Iran"): "🇮🇷",
    _normalizar_texto("Irã"): "🇮🇷",
    _normalizar_texto("IR"): "🇮🇷",
    _normalizar_texto("IRN"): "🇮🇷",
    _normalizar_texto("New Zealand"): "🇳🇿",
    _normalizar_texto("Nova Zelândia"): "🇳🇿",
    _normalizar_texto("NZ"): "🇳🇿",
    _normalizar_texto("NZL"): "🇳🇿",
    _normalizar_texto("Austria"): "🇦🇹",
    _normalizar_texto("Áustria"): "🇦🇹",
    _normalizar_texto("AT"): "🇦🇹",
    _normalizar_texto("AUT"): "🇦🇹",
    _normalizar_texto("Norway"): "🇳🇴",
    _normalizar_texto("Noruega"): "🇳🇴",
    _normalizar_texto("NO"): "🇳🇴",
    _normalizar_texto("NOR"): "🇳🇴",
    _normalizar_texto("Croatia"): "🇭🇷",
    _normalizar_texto("Croácia"): "🇭🇷",
    _normalizar_texto("HR"): "🇭🇷",
    _normalizar_texto("CRO"): "🇭🇷",
    _normalizar_texto("Colombia"): "🇨🇴",
    _normalizar_texto("Colômbia"): "🇨🇴",
    _normalizar_texto("CO"): "🇨🇴",
    _normalizar_texto("COL"): "🇨🇴",
    _normalizar_texto("Cote d'Ivoire"): "🇨🇮",
    _normalizar_texto("Côte d'Ivoire"): "🇨🇮",
    _normalizar_texto("Costa do Marfim"): "🇨🇮",
    _normalizar_texto("CI"): "🇨🇮",
    _normalizar_texto("CIV"): "🇨🇮",
    _normalizar_texto("Ghana"): "🇬🇭",
    _normalizar_texto("Gana"): "🇬🇭",
    _normalizar_texto("GH"): "🇬🇭",
    _normalizar_texto("GHA"): "🇬🇭",
    _normalizar_texto("Panama"): "🇵🇦",
    _normalizar_texto("Panamá"): "🇵🇦",
    _normalizar_texto("PA"): "🇵🇦",
    _normalizar_texto("PAN"): "🇵🇦",
    _normalizar_texto("Uzbekistan"): "🇺🇿",
    _normalizar_texto("Uzbequistão"): "🇺🇿",
    _normalizar_texto("UZ"): "🇺🇿",
    _normalizar_texto("UZB"): "🇺🇿",
    _normalizar_texto("DR Congo"): "🇨🇩",
    _normalizar_texto("RD Congo"): "🇨🇩",
    _normalizar_texto("Congo"): "🇨🇩",
    _normalizar_texto("CD"): "🇨🇩",
    _normalizar_texto("COD"): "🇨🇩",
    _normalizar_texto("Cabo Verde"): "🇨🇻",
    _normalizar_texto("CV"): "🇨🇻",
    _normalizar_texto("CPV"): "🇨🇻",
    _normalizar_texto("Saudi Arabia"): "🇸🇦",
    _normalizar_texto("Arábia Saudita"): "🇸🇦",
    _normalizar_texto("SA"): "🇸🇦",
    _normalizar_texto("KSA"): "🇸🇦",
    _normalizar_texto("Algeria"): "🇩🇿",
    _normalizar_texto("Argélia"): "🇩🇿",
    _normalizar_texto("DZ"): "🇩🇿",
    _normalizar_texto("ALG"): "🇩🇿",
    _normalizar_texto("Jordan"): "🇯🇴",
    _normalizar_texto("Jordania"): "🇯🇴",
    _normalizar_texto("Jordânia"): "🇯🇴",
    _normalizar_texto("JO"): "🇯🇴",
    _normalizar_texto("JOR"): "🇯🇴",
}


def get_flag_emoji(nome_time: str) -> str:
    """Retorna a bandeira correspondente a um nome, apelido ou sigla."""
    if not nome_time:
        return "🏳️"
    return _FLAG_BY_NORMALIZED.get(_normalizar_texto(nome_time), "🏳️")


__all__ = ["get_flag_emoji"]
